name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spatial-data-science/src/platformshell

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./spatial-data-science/src/platformshell
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./spatial-data-science/src/platformshell
      env:
        arcgis_api_key: ${{ secrets.ARCGIS_API_KEY }}
      run: cargo test --verbose
