name: urban_heat_notifier
description: "Users will be notified when they are in a heat-risk area"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  arcgis_maps: ^200.6.0+4426
  async: ^2.11.0
  http: ^1.2.0
  envied: ^0.5.4+1

dev_dependencies:
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.13


flutter:
  uses-material-design: true
 
